# Change these first
owner: jangamprem1704-stack
repo: upptime

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: XDC Innovation Labs Status
  introTitle: "**XDC Innovation Labs** System Status"
  introMessage: This page shows the current status of our monitored services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration